### ISSUE TITLE
Causes Gmail to be locked by Google

### ISSUE THREAD

**Issue by piomar123** [linepogl/opera-gmail#1]
My Google Mail account has been temporarily locked with error 200 (status code 56), probably after using this extension for some time.

**Comment by RailTruck** [comment]
Same thing twice already

**Comment by nwgat** [comment]
sounds like the checking interval is to fast
https://productforums.google.com/forum/#!profile/voice/APn2wQcvbYf2VeM5Mris1rH6lozV0sH59_PM4d6gEiQTsRDP42oXS6RAfPNKSGLOYs4guJ7PUS5y/gmail/TUmb3CRz-D4/o-wSdAxxbZsJ
